version: '3.3'
services:
  go-transip-dyndns:
    image: jlentink/go-transip-dyndns:latest
    container_name: go-transip-dyndns
    volumes:
      - ./go-transip-dyndns.toml:/etc/go-transip-dyndns.toml
    restart: unless-stopped